export const capitals = [
    {
      id: 1,
      question: "What is the capital of Egypt?",
      options: ["Lagos", "London", "Cairo", "Abu Dhabi"],
      answer: 2,
    },
    {
      id: 2,
      question: "What is the capital of Nigeria?",
      options: ["Lome", "Abuja", "Lagos", "Benin"],
      answer: 1,
    },
    {
      id: 3,
      question: "What is the capital of Italy?",
      options: ["Rome", "Naples", "Paris", "Chicago"],
      answer: 0,
    },
    {
      id: 4,
      question: "What is the capital of the United states?",
      options: ["New York", "Dallas", "Washington", "Florida"],
      answer: 2,
    },
    {
      id: 5,
      question: "What is the capital of France?",
      options: ["Zurich", "London", "Lyon", "Paris"],
      answer: 3,
    },
    {
      id: 6,
      question: "What is the capital of Iceland?",
      options: ["Reykjavic", "Glasgow", "Armsterdam", "Heisinki"],
      answer: 0,
    },
    {
      id: 7,
      question: "What is the capital of Switzerland?",
      options: ["Amsterdam", "Bern", "Zurich", "Glasgow"],
      answer: 1,
    },
    {
      id: 8,
      question: "What is the capital of Scotland?",
      options: ["Glasgow", "Turin", "Naples", "Aberdeen"],
      answer: 0,
    },
    {
      id: 9,
      question: "What is the capital of Spain?",
      options: ["Barcelona", "Sevilla", "Getafe", "Madrid"],
      answer: 3,
    },
    {
      id: 10,
      question: "What is the capital of Russia?",
      options: ["St Petersburg", "Moscow", "Sochi", "Altay"],
      answer: 1,
    },
    {
      id: 11,
      question: "What is the capital of England?",
      options: ["Manchester", "Berlin", "Liverpool", "London"],
      answer: 3,
    },
    {
      id: 12,
      question: "What is the capital of Germany?",
      options: ["Berlin", "Frankfurt", "Munich", "Dortmund"],
      answer: 0,
    },
    {
      id: 13,
      question: "What is the capital of Ghana?",
      options: ["Gold coast", "Accra", "Johannesburg", "Cairo"],
      answer: 1,
    },
    {
      id: 14,
      question: "What is the capital of Portugal?",
      options: ["Lisbon", "Porto", "Madrid", "Athens"],
      answer: 0,
    },
    {
      id: 15,
      question: "What is the capital of Netherlands?",
      options: ["Lisbon", "Dunkirk", "Armsterdam", "Sochi"],
      answer: 2,
    },
  ];
  
  export const generals = [
    {
      id: 1,
      question: "ddjdjd",
      options: ["dkd", "djdjd", "dkdk", "ddkdk"],
      answer: 2,
    },
    {
      id: 2,
      question: "ddjdjd",
      options: ["dkd", "djdjd", "dkdk", "ddkdk"],
      answer: 2,
    },
    {
      id: 3,
      question: "ddjdjd",
      options: ["dkd", "djdjd", "dkdk", "ddkdk"],
      answer: 2,
    },
    {
      id: 4,
      question: "ddjdjd",
      options: ["dkd", "djdjd", "dkdk", "ddkdk"],
      answer: 2,
    },
    {
      id: 5,
      question: "ddjdjd",
      options: ["dkd", "djdjd", "dkdk", "ddkdk"],
      answer: 2,
    },
    {
      id: 6,
      question: "ddjdjd",
      options: ["dkd", "djdjd", "dkdk", "ddkdk"],
      answer: 2,
    },
    {
      id: 7,
      question: "ddjdjd",
      options: ["dkd", "djdjd", "dkdk", "ddkdk"],
      answer: 2,
    },
    {
      id: 8,
      question: "ddjdjd",
      options: ["dkd", "djdjd", "dkdk", "ddkdk"],
      answer: 2,
    },
    {
      id: 9,
      question: "ddjdjd",
      options: ["dkd", "djdjd", "dkdk", "ddkdk"],
      answer: 2,
    },
    {
      id: 10,
      question: "ddjdjd",
      options: ["dkd", "djdjd", "dkdk", "ddkdk"],
      answer: 2,
    },
  ];
  export const bbnaijas = [
    {
      id: 1,
      question: "Who won BBNaija Pepperdem?",
      options: ["Phyna", "White Money", "Mercy", "Miracle"],
      answer: 2,
    },
    {
      id: 2,
      question: "Who was the first runner up on BBNaija lockdown?",
      options: ["Dorathy", "Nengi", "Ozo", "Laycon"],
      answer: 0,
    },
    {
      id: 3,
      question: "Who came second in BBNaija Shine Your Eye",
      options: ["White Money", "Liquorose", "Emma", "Pere"],
      answer: 1,
    },
    {
      id: 4,
      question: "Who won BBNaija See Gobe?",
      options: ["Miracle", "Laycon", "Mercy", "Efe"],
      answer: 3,
    },
    {
      id: 5,
      question: "Which of these housemates was never disqualified?",
      options: ["Isilomo", "Khloe", "Tacha", "Erica"],
      answer: 0,
    },
    {
      id: 6,
      question: "Who was the last to be evicted in BBNaija allstars?",
      options: ["Mercy", "Ilebaye", "CeeC", "Adekunle"],
      answer: 2,
    },
    {
      id: 7,
      question: "Who was the top male housemate in BBNaija pepperdem",
      options: ["Seyi", "Frodd", "Mike", "Ike"],
      answer: 2,
    },
    {
      id: 8,
      question: "Who won BBNaija Level up?",
      options: ["Ilebaye", "Whitemoney", "Laycon", "Phyna"],
      answer: 3,
    },
    {
      id: 9,
      question: "Who was the last male housemate on BBNaija level up",
      options: ["Pere", "Bryan", "Adekunle", "Hermes"],
      answer: 1,
    },
    {
      id: 10,
      question: "Who won BBNaija Shine your eye",
      options: ["White Money", "Laycon", "Ilebaye", "Mercy"],
      answer: 0,
    },
  ];